### ISSUE TITLE
Unable to find package Microsoft.NETCore.App with version(>=3.0.0)

### ISSUE THREAD

**Issue by HADDADENICAR** [brianlagunas/ConvertProjectToCore3#5]
I am trying to migrate my WPF(.net framework) project to WPF(.net core 3).
So i have installed [Your Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=BrianLagunas.ConvertProjectToNETCore3) and i m now able to create a new Wpf(.net core) project , but the problem starts when i add a nuget package ! , VS throws me this error :

	Unable to find package Microsoft.NETCore.App with version (>= 3.0.0-preview6-27730-01)
    - Found 69 version(s) in nuget.org [ Nearest version: 3.0.0-preview5-27626-15 ]
    - Found 0 version(s) in Microsoft Visual Studio Offline Packages	TestwpfCore	C:\Users\sintware\source\repos\TestwpfCore\TestwpfCore\TestwpfCore.csproj	1

**Comment by brianlagunas** [comment]
Do you have the latest version of .NET Core 3 installed?

**Comment by HADDADENICAR** [comment]
yes, but apparently the problem is triggred because i installed nuget packages that are base on .NetFramework or .NetCore2:
ex : mahapps metro  and Abp

**Comment by brianlagunas** [comment]
ahhh... good to know it's not the extension 😄
