### ISSUE TITLE
Value cannot be null. Parameter name: input

### ISSUE THREAD

**Issue by mu88** [brianlagunas/ConvertProjectToCore3#6]
I have a very large WPF solution based on .NET 4.5, but I'd like to give it a try and port to .NET Core 3. After installing the extension both into VS 2019 and VS 2019 Preview, the conversion fails with the following error:
![2019-07-30_15h26_08](https://user-images.githubusercontent.com/4560672/62132998-5cbec200-b2de-11e9-8466-5a65e799712e.png)

**Comment by brianlagunas** [comment]
Thanks for reporting this issue, however, without a sample app to reproduce the issue I will not be able to find the source and fix it.
